### ISSUE TITLE
Create Low fidelity wireframes using the User Flow and User Stories as a guide. View link to flow in description

### ISSUE THREAD

**Issue by Aajibolah** [tbf-challenge/teamwork-uiux#1]
Link to User Flow on [Miro ](https://miro.com/app/board/uXjVOmOYnfc=/?share_link_id=460656057490)

Link to User Stories on [Google Docs](https://docs.google.com/document/d/1jNWNUHeZuAzjPvsyyfFSgcqlxMG8EWIbYOzoqLJgFRg/edit?usp=sharing)

**Comment by Teravelli** [comment]
duly noted boss. we will soon kick start project
